name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.7
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle and capture output
      run: ./gradlew build --info --stacktrace > build_output.log 2>&1
      continue-on-error: true

    - name: Display compilation errors
      if: failure()
      run: |
        echo "Compilation Errors:"
        cat build_output.log | grep -A 10 "error:"
        echo "Full error output:"
        cat build_output.log

    - name: List build directory contents
      run: ls -R build/libs
      
    - name: Upload compiled JAR
      uses: actions/upload-artifact@v3
      with:
        name: Smn-B4
        path: build/libs/Smn-B4.jar
        if-no-files-found: warn

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gradle-logs
        path: |
          build_output.log
          build/reports/**/*
          build/test-results/**/*
          *.log
