name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.9
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Compile Java with detailed output
      run: |
        ./gradlew compileJava --stacktrace --info -Xlint:deprecation -Xlint:unchecked > compile_output.log 2>&1 || true
        echo "Compilation Errors and Warnings:"
        cat compile_output.log | grep -E "error:|warning:|What went wrong:|Cause:" | head -n 50
    
    - name: Full build attempt
      run: ./gradlew build --stacktrace --info
      continue-on-error: true
      
    - name: Upload compilation log
      uses: actions/upload-artifact@v4
      with:
        name: compile-log
        path: compile_output.log
    
    - name: Upload final JAR
      uses: actions/upload-artifact@v4
      with:
        name: Smn-B4-final
        path: build/final/Smn-B4-final.jar
        if-no-files-found: warn
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-logs
        path: |
          build/reports/**/*
          build/test-results/**/*
          *.log
