name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.4.1
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Display Gradle version and system info
      run: |
        ./gradlew --version
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "PATH: $PATH"
    
    - name: Clean Gradle cache
      run: ./gradlew clean --info
    
    - name: Build with Gradle (verbose)
      run: |
        ./gradlew build --debug --stacktrace \
        -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" \
        -Dorg.gradle.parallel=true \
        -Dorg.gradle.configureondemand=true
      continue-on-error: true
    
    - name: Display Gradle build output
      if: always()
      run: |
        if [ -f build/build_output.log ]; then
          cat build/build_output.log
        else
          echo "build_output.log not found. Displaying gradle.log:"
          cat $HOME/.gradle/daemon/4.4.1/daemon-*.out.log
        fi
    
    - name: Display compilation errors
      if: failure()
      run: |
        echo "Compilation Errors:"
        grep -A 10 "\[ERROR\]" $HOME/.gradle/daemon/4.4.1/daemon-*.out.log || echo "No [ERROR] found in Gradle logs"
    
    - name: List files in project directory
      if: always()
      run: ls -R
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gradle-logs
        path: |
          build/build_output.log
          $HOME/.gradle/daemon/4.4.1/daemon-*.out.log
          build/reports/**/*
          build/test-results/**/*
          *.log
    
    - name: Upload compiled JAR
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Smn-B4
        path: build/libs/*.jar
