name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.7
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build --info
    
    - name: List entire build directory
      run: find build -type f
      
    - name: Upload compiled JAR
      uses: actions/upload-artifact@v3
      with:
        name: Smn-B4
        path: build/**/*.jar
        if-no-files-found: warn

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gradle-logs
        path: |
          build/reports/**/*
          build/test-results/**/*
          *.log
