name: Java CI with Gradle

on:
  push:
    paths:
      - '**/*.java'
      - '**/*.json'
      - 'gradle/**'
      - 'build.gradle'
  pull_request:
    paths:
      - '**/*.java'
      - '**/*.json'
      - 'gradle/**'
      - 'build.gradle'
  workflow_dispatch:  # Allows the workflow to be manually triggered

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Validate Gradle wrapper
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    # Step 3: Set up JDK 8 (necessary for Minecraft 1.8.9 modding)
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'   # You can also use 'adopt', 'zulu', etc.
        java-version: '8'
        cache: 'gradle'

    # Step 4: Grant execute permission for gradlew (important for Linux environments)
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 5: Setup Gradle environment
    - name: Setup Gradle
      uses: gradle/setup-gradle@v3
      with:
        gradle-version: 4.7  # Specify the Gradle version to use (since you're using Gradle 4.7)

    # Step 6: Run the Gradle build process
    - name: Execute Gradle build
      run: ./gradlew build --stacktrace

    # Step 7: Upload the built JAR as an artifact
    - name: Upload JAR as GitHub Actions artifact
      uses: actions/upload-artifact@v4
      with:
        name: Built-JAR
        path: build/libs/*.jar
