name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.7
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Display Gradle version and project structure
      run: |
        ./gradlew --version
        echo "Project structure:"
        ls -R
    
    - name: Build with Gradle
      run: ./gradlew build --info --stacktrace
    
    - name: List build directory contents
      run: |
        echo "Build directory contents:"
        ls -R build || echo "build directory does not exist"
      
    - name: Upload final JAR
      uses: actions/upload-artifact@v4
      with:
        name: Smn-B4-final
        path: build/final/Smn-B4-final.jar
        if-no-files-found: warn
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-logs
        path: |
          build/reports/**/*
          build/test-results/**/*
          *.log
