name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 4.7
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Display Gradle version
      run: ./gradlew --version
    
    - name: Clean Gradle cache
      run: ./gradlew clean --info

    - name: Build with Gradle (verbose)
      run: ./gradlew build --info --stacktrace -Dorg.gradle.debug=true -Dorg.gradle.daemon=false

    - name: Run compilations with unchecked operations details
      if: failure()
      run: ./gradlew compileJava -Xlint:unchecked --info --stacktrace
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gradle-logs
        path: |
          .gradle/daemon
          build/reports
          *.log
    
    - name: Upload compiled JAR
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Smn-B4
        path: build/libs/Smn-B4.jar
