name: Build and Upload JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: List contents of build/libs directory
      run: ls -R build/libs

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: SmnB4-JAR
        path: build/libs/Smn-B4.jar

    - name: Check for uploaded artifacts
      run: |
        if [ -z "$(find build/libs -name 'Smn-*.jar' -print -quit)" ]; then
          echo "No Smn-*.jar files found in build/libs directory"
          exit 1
        else
          echo "Smn-*.jar files found and should be uploaded as artifacts"
        fi
